#!/usr/bin/env bash
# This script displays a list of currently running processes, including those that don't have a TTY.

echo "User-oriented list of running processes, including those without a TTY:"
ps -efH
